services:
  postgres:
    image: 'postgres:18.4'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '9876:5432'
    volumes:
      - pgdata:/var/lib/postgresql/

  redis:
    image: redis:8.8.0
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: redis-server --requirepass redisPassword --appendonly yes
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4.3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitUser
      - RABBITMQ_DEFAULT_PASS=rabbitPassword
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v3.6.0
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:12.2.0
    container_name: grafana
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

volumes:
  pgdata:
  redis-data:
    driver: local
  rabbitmq-data:
  grafana-data:
