services:
  postgres:
    image: 'postgres:18.4'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '9876:5432'
    volumes:
      - pgdata:/var/lib/postgresql/

  redis:
    image: redis:8.8.0
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: redis-server --requirepass redisPassword --appendonly yes
    restart: unless-stopped


volumes:
  pgdata:
  redis-data:
    driver: local
