spring.application.name=AdvancedCrud

spring.docker.compose.enabled=false

jwt.private-key=classpath:keys/private.pem
jwt.public-key=classpath:keys/public.pem
jwt.issuer=advanced-crud-api
jwt.access-token-ttl-minutes=15

spring.datasource.url=jdbc:postgresql://localhost:9876/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=redisPassword

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=rabbitUser
spring.rabbitmq.password=rabbitPassword
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=1000
spring.rabbitmq.listener.simple.retry.multiplier=2
spring.rabbitmq.listener.simple.retry.max-interval=10000
spring.rabbitmq.listener.simple.default-requeue-rejected=false