spring.application.name=AdvancedCrud

jwt.private-key=classpath:keys/private.pem
jwt.public-key=classpath:keys/public.pem
jwt.issuer=advanced-crud-api
jwt.access-token-ttl-minutes=15

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=redisPassword